import Topbar from "@/components/admin/Topbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
